import type { ResumeSections } from '../types';
import { uuidv4 } from './helpers';

export const softwareEngineerSample = (): ResumeSections => ({
  personalInfo: {
    name: 'Alex Rivera',
    title: 'Senior Full Stack & Cloud Architect',
    email: 'alex.rivera@devcloud.io',
    phone: '+1 (415) 890-3412',
    address: 'San Francisco, CA',
    linkedin: 'alexrivera-cloud',
    github: 'arivera-dev',
    portfolio: 'https://alexrivera.io',
    website: 'https://alexrivera.io',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    summary: 'Senior Cloud Architect & Full Stack Engineer with **8+ years of experience** building high-concurrency microservices, distributed systems, and AI-enabled web platforms. Proven track record scaling applications from 10k to **15M+ daily active users** with sub-80ms latency while mentoring engineering orgs and optimizing cloud infrastructure costs by 35%.',
  },
  experience: [
    {
      id: uuidv4(),
      company: 'Apex Cloud Systems',
      position: 'Staff Software Engineer',
      location: 'San Francisco, CA',
      startDate: '2021-04',
      endDate: '',
      current: true,
      description: 'Lead architect for the core cloud orchestration engine handling over 1.8B daily telemetry events.',
      bullets: [
        'Architected and deployed a multi-tenant event-driven microservices platform on **AWS EKS (Kubernetes)** using Go and Node.js, reducing median API response time by **42%**.',
        'Spearheaded the migration of monolithic Postgres clusters to distributed CockroachDB instances across 3 AWS regions, achieving **99.999% uptime** and zero-downtime deployments.',
        'Mentored 14 junior and mid-level engineers across 3 squads, establishing rigorous CI/CD standards and automated security scanning with GitHub Actions.',
        'Optimized AWS cloud infrastructure provisioning using Terraform, cutting annual compute costs by **$340,000** without sacrificing throughput.',
      ],
    },
    {
      id: uuidv4(),
      company: 'Stripe API & Billing Labs',
      position: 'Senior Backend Engineer',
      location: 'Seattle, WA (Remote)',
      startDate: '2018-06',
      endDate: '2021-03',
      current: false,
      description: 'Core developer for merchant billing pipelines and automated fraud detection APIs.',
      bullets: [
        'Engineered high-concurrency payment processing pipelines handling **$140M+ in monthly transaction volume** with strict ACID compliance.',
        'Designed and implemented real-time webhook delivery engines with Redis and Kafka, achieving **99.98% delivery success rates** under burst traffic.',
        'Collaborated directly with product managers and enterprise customers to design public REST & GraphQL APIs, driving a **30% increase in developer onboarding efficiency**.',
      ],
    },
    {
      id: uuidv4(),
      company: 'Quantum Dev Studios',
      position: 'Full Stack Software Engineer',
      location: 'Austin, TX',
      startDate: '2016-01',
      endDate: '2018-05',
      current: false,
      description: 'Built customer-facing web dashboards and real-time analytics portals.',
      bullets: [
        'Developed responsive single-page applications using **React, TypeScript, and Redux**, improving mobile user engagement by **45%**.',
        'Created automated RESTful APIs with Node.js and Express backed by MongoDB and PostgreSQL.',
        'Implemented automated end-to-end testing suites using Cypress and Jest, raising code coverage from 42% to **88%**.',
      ],
    },
  ],
  education: [
    {
      id: uuidv4(),
      institution: 'University of California, Berkeley',
      degree: 'Bachelor of Science in Computer Science',
      field: 'Computer Science & Software Engineering',
      startDate: '2012-09',
      endDate: '2016-05',
      current: false,
      gpa: '3.86',
      description: 'President of Cloud Computing Club. Senior Thesis: Distributed Consensus Algorithms under Network Partitions.',
    },
  ],
  projects: [
    {
      id: uuidv4(),
      name: 'KubeMonitor - Open Source Telemetry Tool',
      description: 'Real-time Kubernetes pod health and resource anomaly visualization engine.',
      technologies: ['Go', 'React', 'Prometheus', 'Kubernetes', 'WebSockets'],
      githubUrl: 'https://github.com/arivera-dev/kubemonitor',
      liveUrl: 'https://kubemonitor.dev',
      startDate: '2022-08',
      endDate: '2023-11',
      bullets: [
        'Garnered over **3,400 GitHub stars** and 120+ active community contributors across 20 countries.',
        'Engineered a lightweight eBPF kernel agent in C/Go that collects container metrics with **<0.8% CPU overhead**.',
      ],
    },
    {
      id: uuidv4(),
      name: 'AI Code Assistant CLI',
      description: 'Terminal-based LLM pair programmer with AST semantic code understanding.',
      technologies: ['Rust', 'Python', 'OpenAI API', 'AST Parsing'],
      githubUrl: 'https://github.com/arivera-dev/ai-code-cli',
      liveUrl: '',
      startDate: '2023-12',
      endDate: '',
      bullets: [
        'Built a high-performance Rust CLI that indexes local git repositories and provides instant context-aware code suggestions.',
      ],
    },
  ],
  skills: [
    {
      id: uuidv4(),
      category: 'Languages & Core Tech',
      items: ['TypeScript', 'Go (Golang)', 'Python', 'Rust', 'JavaScript (ES6+)', 'SQL', 'HTML5 & CSS3'],
    },
    {
      id: uuidv4(),
      category: 'Cloud & DevOps',
      items: ['AWS (EKS, Lambda, S3, RDS)', 'Docker & Kubernetes', 'Terraform', 'CI/CD (GitHub Actions)', 'Prometheus & Grafana'],
    },
    {
      id: uuidv4(),
      category: 'Frameworks & Databases',
      items: ['React & Next.js', 'Node.js & Express', 'PostgreSQL', 'Redis & Kafka', 'GraphQL & REST APIs', 'CockroachDB'],
    },
  ],
  certificates: [
    {
      id: uuidv4(),
      name: 'AWS Certified Solutions Architect – Professional',
      issuer: 'Amazon Web Services',
      date: '2023',
      url: 'https://aws.amazon.com/verification',
      credentialId: 'AWS-SAP-981204',
    },
    {
      id: uuidv4(),
      name: 'Certified Kubernetes Administrator (CKA)',
      issuer: 'Linux Foundation / CNCF',
      date: '2022',
      url: 'https://cncf.io/certification',
      credentialId: 'LF-CKA-44310',
    },
  ],
  achievements: [
    {
      id: uuidv4(),
      title: 'First Place Winner — AWS Global Serverless Hackathon',
      date: '2022',
      description: 'Built a real-time serverless disaster response coordination platform competing against 850+ international teams.',
    },
  ],
  languages: [
    { id: uuidv4(), name: 'English', proficiency: 'Native / Bilingual' },
    { id: uuidv4(), name: 'Spanish', proficiency: 'Professional Working' },
  ],
  interests: [
    { id: uuidv4(), name: 'Open Source Systems Architecture' },
    { id: uuidv4(), name: 'Competitive Chess (2050 ELO)' },
    { id: uuidv4(), name: 'High Altitude Mountaineering' },
  ],
  references: [],
  customSections: [],
});

export const productManagerSample = (): ResumeSections => ({
  personalInfo: {
    name: 'Sarah Jenkins',
    title: 'VP of Product Management — AI & Growth SaaS',
    email: 's.jenkins@productlead.co',
    phone: '+1 (646) 720-9182',
    address: 'New York, NY',
    linkedin: 'sarah-jenkins-pm',
    github: '',
    portfolio: 'https://sarahjenkins.product',
    website: 'https://sarahjenkins.product',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    summary: 'Transformational **Senior Product Leader with 9+ years** spearheading B2B & B2C SaaS product strategies, AI feature integration, and cross-functional engineering execution. Successfully scaled flagship products from **$4M to $38M ARR** while leading 25+ designers, product managers, and data scientists across global offices.',
  },
  experience: [
    {
      id: uuidv4(),
      company: 'Elevate AI & Analytics',
      position: 'VP of Product Management',
      location: 'New York, NY',
      startDate: '2022-01',
      endDate: '',
      current: true,
      description: 'Direct the entire AI product portfolio, roadmap execution, and growth monetization strategies.',
      bullets: [
        'Formulated and executed the product roadmap for an enterprise AI analytics suite, driving **280% YoY revenue growth** and securing 45 new Fortune 500 accounts.',
        'Orchestrated the launch of a generative AI workflow assistant, resulting in **140,000 active weekly users** within 6 months of release and boosting Net Retention Rate (NRR) to **126%**.',
        'Spearheaded a cross-functional organization of **30+ PMs, UX researchers, and engineering leads**, instituting OKR-driven sprint cadences and continuous discovery loops.',
        'Led strategic pricing and packaging restructuring that lifted average contract value (ACV) by **34%** while decreasing customer churn by 4.2 percentage points.',
      ],
    },
    {
      id: uuidv4(),
      company: 'HubSpot & Marketing Cloud Labs',
      position: 'Senior Group Product Manager',
      location: 'Boston, MA',
      startDate: '2019-03',
      endDate: '2021-12',
      current: false,
      description: 'Owned the core growth onboarding funnel and self-service expansion engine.',
      bullets: [
        'Redesigned the self-serve onboarding journey using product-led growth (PLG) methodologies, increasing free-to-paid conversion from **3.8% to 8.4%** across 1.2M users.',
        'Collaborated with data science teams to deploy predictive lead-scoring models directly into customer CRM dashboards, driving **$12M in expansion ARR**.',
        'Conducted 150+ qualitative customer discovery interviews and quantitative A/B tests to identify high-friction UI drop-offs.',
      ],
    },
    {
      id: uuidv4(),
      company: 'Veloce Commerce Solutions',
      position: 'Product Manager',
      location: 'New York, NY',
      startDate: '2016-07',
      endDate: '2019-02',
      current: false,
      description: 'Managed checkout optimization and mobile web experiences.',
      bullets: [
        'Spearheaded the 1-click checkout redesign, slashing cart abandonment rates by **18%** across mobile and desktop devices.',
        'Partnered closely with agile engineering squads using Jira and Figma to deliver features **15% ahead of projected release milestones**.',
      ],
    },
  ],
  education: [
    {
      id: uuidv4(),
      institution: 'Columbia Business School',
      degree: 'Master of Business Administration (MBA)',
      field: 'Product Strategy & Technology Entrepreneurship',
      startDate: '2014-09',
      endDate: '2016-05',
      current: false,
      gpa: '3.92',
      description: 'Dean’s List. Co-founder of Columbia Tech & Venture Club.',
    },
    {
      id: uuidv4(),
      institution: 'Cornell University',
      degree: 'Bachelor of Arts in Economics & Statistics',
      field: 'Quantitative Economics',
      startDate: '2010-09',
      endDate: '2014-05',
      current: false,
      gpa: '3.88',
      description: 'Magna Cum Laude.',
    },
  ],
  projects: [
    {
      id: uuidv4(),
      name: 'ProductLeap - PM Framework Workshop Series',
      description: 'Mentorship program and open-source playbook for aspiring product managers.',
      technologies: ['Figma', 'Product Strategy', 'Notion', 'Analytics'],
      githubUrl: '',
      liveUrl: 'https://sarahjenkins.product/mentorship',
      startDate: '2021-05',
      endDate: '',
      bullets: [
        'Mentored 40+ early-career product managers, helping 28 land senior PM roles at top-tier tech companies.',
        'Published a viral framework on product prioritization viewed by **250,000+ industry professionals** on LinkedIn and Medium.',
      ],
    },
  ],
  skills: [
    {
      id: uuidv4(),
      category: 'Product Strategy & Execution',
      items: ['Product Roadmap & Vision', 'Product-Led Growth (PLG)', 'Agile / Scrum & OKRs', 'A/B Testing & Experimentation', 'Go-To-Market (GTM) Strategy', 'Enterprise B2B Pricing'],
    },
    {
      id: uuidv4(),
      category: 'Analytics & UX Tools',
      items: ['Amplitude & Mixpanel', 'SQL & Tableau', 'Figma & Wireframing', 'Jira & Linear', 'User Discovery & Interviews', 'Cohort Retention Analysis'],
    },
  ],
  certificates: [
    {
      id: uuidv4(),
      name: 'Certified Scrum Product Owner (CSPO)',
      issuer: 'Scrum Alliance',
      date: '2020',
      url: 'https://scrumalliance.org',
      credentialId: 'CSPO-884102',
    },
  ],
  achievements: [
    {
      id: uuidv4(),
      title: 'Named Top 50 Product Leaders to Watch — Product Excellence Awards',
      date: '2023',
      description: 'Recognized by Product Excellence Council for outstanding leadership and generative AI user experience innovation.',
    },
  ],
  languages: [
    { id: uuidv4(), name: 'English', proficiency: 'Native / Bilingual' },
    { id: uuidv4(), name: 'French', proficiency: 'Professional Working' },
  ],
  interests: [
    { id: uuidv4(), name: 'Tech Mentorship & Angel Investing' },
    { id: uuidv4(), name: 'Marathon Running (NYC Marathon Finisher)' },
    { id: uuidv4(), name: 'Modern Architecture Photography' },
  ],
  references: [],
  customSections: [],
});

export const financialAnalystSample = (): ResumeSections => ({
  personalInfo: {
    name: 'David Chen, CFA',
    title: 'Lead Financial Analyst & Corporate Strategy Manager',
    email: 'david.chen@finstrategy.org',
    phone: '+1 (312) 540-8821',
    address: 'Chicago, IL',
    linkedin: 'david-chen-cfa',
    github: '',
    portfolio: 'https://davidchenfin.com',
    website: 'https://davidchenfin.com',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    summary: 'Chartered Financial Analyst (**CFA Charterholder**) with **7+ years of experience** in financial forecasting, M&A valuation, capital allocation, and FP&A leadership across Fortune 500 financial and fintech institutions. Adept at building multi-billion dollar DCF valuation models, reducing operational overhead by **$14M+**, and presenting strategic insights to C-suite executives and board members.',
  },
  experience: [
    {
      id: uuidv4(),
      company: 'Vanguard Capital & Asset Management',
      position: 'Lead Financial Analyst — Corporate Strategy',
      location: 'Chicago, IL',
      startDate: '2021-08',
      endDate: '',
      current: true,
      description: 'Lead analyst for corporate financial planning, quarterly guidance, and M&A evaluations across North America.',
      bullets: [
        'Built dynamic 3-statement financial models and DCF valuations for **$4.2B+ in potential strategic acquisitions**, directly informing board execution decisions.',
        'Spearheaded the annual corporate budgeting process across 12 divisions managing **$850M in operating expenses**, identifying **$14.5M in cost efficiency savings**.',
        'Automated monthly executive variance reporting using Python, SQL, and PowerBI, slashing reporting turnaround time by **70%** (`from 5 days to 1.5 days`).',
        'Presented quarterly financial guidance and risk mitigation forecasts directly to the CFO and Executive Advisory Board.',
      ],
    },
    {
      id: uuidv4(),
      company: 'Morgan & Sterling Investment Banking',
      position: 'Senior Financial Analyst — M&A Advisory',
      location: 'New York, NY',
      startDate: '2018-06',
      endDate: '2021-07',
      current: false,
      description: 'Executed valuation modeling, due diligence, and deal structuring for mid-market financial transactions.',
      bullets: [
        'Executed valuation modeling (LBO, Trading Multiples, Precedent Transactions) for **8 closed M&A deals** with aggregate enterprise value exceeding **$1.6B**.',
        'Led comprehensive financial and tax due diligence, uncovering **$3.8M in hidden working capital liabilities** during a major fintech acquisition.',
        'Mentored 6 first-year analysts in Excel financial modeling best practices, accounting principles, and pitchbook design.',
      ],
    },
    {
      id: uuidv4(),
      company: 'Prudential Financial Partners',
      position: 'FP&A Analyst',
      location: 'Chicago, IL',
      startDate: '2016-06',
      endDate: '2018-05',
      current: false,
      description: 'Conducted quarterly forecasting and capital expenditure evaluations.',
      bullets: [
        'Analyzed capital expenditure returns (NPV, IRR) across 40+ branch expansion initiatives, improving capital allocation efficiency by **16%**.',
        'Reconciled complex general ledger accounts and prepared consolidated SEC 10-Q and 10-K compliance filings.',
      ],
    },
  ],
  education: [
    {
      id: uuidv4(),
      institution: 'University of Chicago — Booth School of Business',
      degree: 'Master of Business Administration (MBA)',
      field: 'Analytic Finance & Strategic Management',
      startDate: '2019-09',
      endDate: '2021-06',
      current: false,
      gpa: '3.95',
      description: 'High Honors. President of Investment Banking Group.',
    },
    {
      id: uuidv4(),
      institution: 'Northwestern University',
      degree: 'Bachelor of Arts in Economics & Accounting',
      field: 'Economics',
      startDate: '2012-09',
      endDate: '2016-05',
      current: false,
      gpa: '3.90',
      description: 'Summa Cum Laude.',
    },
  ],
  projects: [],
  skills: [
    {
      id: uuidv4(),
      category: 'Financial Modeling & Valuation',
      items: ['DCF & LBO Modeling', 'M&A Due Diligence', 'FP&A Forecasting', 'Capital Allocation & IRR', '3-Statement Financial Modeling', 'Variance & Sensitivity Analysis'],
    },
    {
      id: uuidv4(),
      category: 'Technical & BI Tools',
      items: ['Advanced Excel (VBA, Macros)', 'Python for Financial Analysis', 'SQL & Data Warehousing', 'PowerBI & Tableau', 'Bloomberg Terminal', 'Capital IQ'],
    },
  ],
  certificates: [
    {
      id: uuidv4(),
      name: 'Chartered Financial Analyst (CFA®) Charterholder',
      issuer: 'CFA Institute',
      date: '2020',
      url: 'https://cfainstitute.org',
      credentialId: 'CFA-498120',
    },
    {
      id: uuidv4(),
      name: 'Financial Modeling & Valuation Analyst (FMVA®)',
      issuer: 'Corporate Finance Institute (CFI)',
      date: '2018',
      url: 'https://corporatefinanceinstitute.com',
      credentialId: 'FMVA-99312',
    },
  ],
  achievements: [
    {
      id: uuidv4(),
      title: 'Top Analyst Award — Vanguard Corporate Strategy Group',
      date: '2023',
      description: 'Awarded for exceptional leadership in identifying $14.5M in operational savings and automating FP&A reporting.',
    },
  ],
  languages: [
    { id: uuidv4(), name: 'English', proficiency: 'Native / Bilingual' },
    { id: uuidv4(), name: 'Mandarin Chinese', proficiency: 'Native / Bilingual' },
  ],
  interests: [
    { id: uuidv4(), name: 'Algorithmic Portfolio Backtesting' },
    { id: uuidv4(), name: 'Competitive Squash & Golf' },
    { id: uuidv4(), name: 'Behavioral Economics Literature' },
  ],
  references: [],
  customSections: [],
});

export const indianFresherSample = (): ResumeSections => ({
  personalInfo: {
    name: 'Aarav Sharma',
    title: 'Software Development Engineer (SDE) Graduate',
    email: 'aarav.sharma@btech-alumni.in',
    phone: '+91 98765 43210',
    address: 'Bengaluru, Karnataka, India',
    linkedin: 'aarav-sharma-dev',
    github: 'aaravsharma-dev',
    portfolio: 'https://aaravsharma.dev',
    website: 'https://aaravsharma.dev',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    summary: 'Enthusiastic and highly motivated B.Tech Computer Science & Engineering graduate with a CGPA of 8.92. Hands-on experience developing full-stack web applications and implementing data pipelines. Well-versed in Java, JavaScript, Python, and SQL databases. Strong problem-solving abilities and eager to contribute to high-performance product teams.',
  },
  experience: [
    {
      id: uuidv4(),
      company: 'Tata Consultancy Services (TCS)',
      position: 'Software Developer Intern',
      location: 'Bengaluru, India',
      startDate: '2024-01',
      endDate: '2024-06',
      current: false,
      description: 'Worked in the cloud services division to optimize administration dashboards.',
      bullets: [
        'Developed interactive frontend components using React.js and Tailwind CSS, increasing page responsiveness by 25%.',
        'Refactored legacy database queries in MySQL, resulting in an 18% reduction in telemetry page loading times.',
        'Wrote end-to-end automation scripts in Selenium covering 12 critical user login and checkout flows.',
      ],
    },
  ],
  education: [
    {
      id: uuidv4(),
      institution: 'Vellore Institute of Technology (VIT)',
      degree: 'B.Tech in Computer Science & Engineering',
      field: 'Computer Science',
      startDate: '2020-07',
      endDate: '2024-05',
      current: false,
      gpa: '8.92 CGPA',
      description: 'Relevant coursework: Data Structures, Analysis of Algorithms, Database Management Systems, Cloud Computing.',
    },
    {
      id: uuidv4(),
      institution: 'Delhi Public School (DPS), R.K. Puram',
      degree: 'Class XII (CBSE Board)',
      field: 'Science Stream (PCM / Computer Science)',
      startDate: '2018-04',
      endDate: '2020-03',
      current: false,
      gpa: '95.4%',
      description: 'Secured Rank 1 in school science exhibition for IoT-based smart farming prototype.',
    },
  ],
  projects: [
    {
      id: uuidv4(),
      name: 'E-Commerce Platform for Local Artisans',
      description: 'Web application supporting localized business listings and digital payments.',
      technologies: ['React.js', 'Node.js', 'Express', 'MongoDB', 'Razorpay API'],
      githubUrl: 'https://github.com/aaravsharma-dev/vocal-for-local',
      liveUrl: 'https://vocalforlocal.co.in',
      startDate: '2023-08',
      endDate: '2023-11',
      bullets: [
        'Built full-stack ordering portal allowing 40+ local merchants to create stores and process orders online.',
        'Integrated Razorpay payment gateway with secure webhook validation protocols.',
      ],
    },
  ],
  skills: [
    {
      id: uuidv4(),
      category: 'Programming Languages',
      items: ['Java (Core + Advanced)', 'JavaScript / TypeScript', 'Python', 'C++'],
    },
    {
      id: uuidv4(),
      category: 'Web Technologies & Frameworks',
      items: ['React.js', 'Node.js', 'Express.js', 'Tailwind CSS', 'Redux Toolkit'],
    },
    {
      id: uuidv4(),
      category: 'Databases & Tools',
      items: ['MySQL', 'MongoDB', 'Git / GitHub', 'Docker', 'Postman'],
    },
  ],
  certificates: [
    {
      id: uuidv4(),
      name: 'Oracle Certified Associate Java Programmer',
      issuer: 'Oracle Corporation',
      date: '2023',
      url: '',
      credentialId: 'OCP-882312',
    },
  ],
  achievements: [
    {
      id: uuidv4(),
      title: 'Winner - Smart India Hackathon (SIH)',
      date: '2023',
      description: 'First place out of 150 teams for developing an automated soil health analysis app for remote farmers.',
    },
  ],
  languages: [
    { id: uuidv4(), name: 'English', proficiency: 'Professional Working' },
    { id: uuidv4(), name: 'Hindi', proficiency: 'Native / Bilingual' },
  ],
  interests: [
    { id: uuidv4(), name: 'Competitive Coding (CodeChef / LeetCode)' },
    { id: uuidv4(), name: 'IoT Prototypes & Automation' },
  ],
  references: [],
  customSections: [],
});

export const blankResumeSample = (): ResumeSections => ({
  personalInfo: {
    name: '',
    title: '',
    email: '',
    phone: '',
    address: '',
    linkedin: '',
    github: '',
    portfolio: '',
    website: '',
    photo: '',
    summary: '',
  },
  experience: [],
  education: [],
  projects: [],
  skills: [],
  certificates: [],
  achievements: [],
  languages: [],
  interests: [],
  references: [],
  customSections: [],
});
